POST http://localhost:3001/users
Content-Type: application/json

{
    "email": "ravi1234@gmail.com"
}

###

POST http://localhost:3001/forms/waterPollutionForm
Content-Type: application/json

{
    "email": "rav1234@gmail.com",
    "location": ["74.9455", "30.2110"],
    "optionsArray": [0, 1]
}

###

POST http://localhost:3001/forms/airPollutionForm
Content-Type: application/json

{
    "email": "rai1234@gmail.com",
    "location": ["77.02667642994435", "28.60668230501916"],
    "optionsArray": ["a", "b", "c", "d"]
}

###

POST http://localhost:3001/forms/climatePatternsForm
Content-Type: application/json

{
    "email": "ravi1234@gmail.com",
    "location": ["77.02667642994435", "28.60668230501916"],
    "optionsArray": ["a", "b", "c", "d"]
}

###

POST http://localhost:3001/forms/deforestationRateForm
Content-Type: application/json

{
    "email": "ravi1234@gmail.com",
    "location": ["77.02667642994435", "28.60668230501916"],
    "optionsArray": ["a", "b", "c", "d"]
}

###

GET http://localhost:3001/forms/airPollutionForm/data/showmedata


###

POST http://localhost:3001/message
Content-Type: application/json

{
    "email": "ravi1234@gmail.com",
    "message": "Hii"
}